import { StyleSheet } from 'react-native';

export const profileStyles = StyleSheet.create({
  loader: { flex: 1 },
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  content: { padding: 20, paddingBottom: 48 },
  section: { marginBottom: 28 },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#888',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 8,
    marginLeft: 4,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 14,
    overflow: 'hidden',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  rowIcon: { marginRight: 14 },
  rowBody: { flex: 1 },
  rowLabel: { fontSize: 15, fontWeight: '500', color: '#1A1A1A' },
  rowSubLabel: { fontSize: 12, color: '#888', marginTop: 2 },
  rowValue: { fontSize: 14, color: '#555', marginTop: 2 },
  inviteCode: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2D6A4F',
    letterSpacing: 2,
    marginTop: 2,
  },
  iconBtn: { padding: 6, marginLeft: 4 },
  divider: { height: 1, backgroundColor: '#F0F0F0', marginLeft: 50 },
  danger: { color: '#E53935' },
  logQty: { fontSize: 15, fontWeight: '700', minWidth: 32, textAlign: 'right' },
});
